#!/bin/sh
#
# @name Gazebo eft
#
# @type Quadrotor
#

. ${R}etc/init.d/rc.mc_defaults

PX4_SIMULATOR=${PX4_SIMULATOR:=gz}
PX4_GZ_WORLD=${PX4_GZ_WORLD:=default}
PX4_SIM_MODEL=${PX4_SIM_MODEL:=eft}

param set-default SIM_GZ_EN 1

param set-default CA_AIRFRAME 0
param set-default CA_ROTOR_COUNT 4

param set-default CA_ROTOR0_PX 0.49
param set-default CA_ROTOR0_PY 0.48
param set-default CA_ROTOR0_KM  0.05

param set-default CA_ROTOR1_PX -0.47
param set-default CA_ROTOR1_PY -0.48
param set-default CA_ROTOR1_KM  0.05

param set-default CA_ROTOR2_PX 0.49
param set-default CA_ROTOR2_PY -0.48
param set-default CA_ROTOR2_KM -0.05

param set-default CA_ROTOR3_PX -0.47
param set-default CA_ROTOR3_PY 0.48
param set-default CA_ROTOR3_KM -0.05

param set-default SIM_GZ_EC_FUNC1 101
param set-default SIM_GZ_EC_FUNC2 102
param set-default SIM_GZ_EC_FUNC3 103
param set-default SIM_GZ_EC_FUNC4 104

param set-default SIM_GZ_EC_MIN1 50
param set-default SIM_GZ_EC_MIN2 50
param set-default SIM_GZ_EC_MIN3 50
param set-default SIM_GZ_EC_MIN4 50

param set-default SIM_GZ_EC_MAX1 320
param set-default SIM_GZ_EC_MAX2 320
param set-default SIM_GZ_EC_MAX3 320
param set-default SIM_GZ_EC_MAX4 320

param set-default MPC_THR_HOVER 0.60
param set-default NAV_DLL_ACT 2
